#!/opt/local/bin/perl

## There's too much use of source code in strings.
## no critic (RequireInterpolationOfMetachars)

use 5.006001;
use strict;
use warnings;

use Carp qw< confess >;

use File::Slurp qw( read_file );
use PPI::Document ();
use PPI::Document::File ();
use PPI::Dumper ();
use Perl::Critic::Document ();

#-----------------------------------------------------------------------------

our $VERSION = '1.121';

#-----------------------------------------------------------------------------

@ARGV = ($0);
exit main();

sub main{
    for my $file ( @ARGV ) {
        my $doc = PPI::Document->new( $file );
        my $dumper = PPI::Dumper->new( $doc, whitespace => 0, locations => 0 );
        $dumper->print;
        exit;
        my $statement = $doc->find_first( sub { 1 } );
        {use Data::Dumper; local $Data::Dumper::Sortkeys=1; warn Dumper( $statement )}

        while ( $statement = $statement->next_sibling ) {
            {use Data::Dumper; local $Data::Dumper::Sortkeys=1; warn Dumper( $statement )}
        }
    }
}

my $single_quoted_str = 'Quoted string';
my $double_quoted_str = "Quoted string";
my $heredoc = <<'HERE';
String in a heredoc
HERE
